"""empty message

Revision ID: 5cd97881b9f9
Revises: af3dec8cedff
Create Date: 2021-07-10 00:22:29.477742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cd97881b9f9'
down_revision = 'af3dec8cedff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('chips', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'chips')
    # ### end Alembic commands ###
