"""empty message

Revision ID: af3dec8cedff
Revises: a40f803c969d
Create Date: 2021-07-09 21:34:56.839831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af3dec8cedff'
down_revision = 'a40f803c969d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('value', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'value')
    # ### end Alembic commands ###
